title: "Dator-kompendier"
remote_theme: just-the-docs/just-the-docs
search_enabled: true

url: "https://cesarpetter.github.io"
baseurl: "/dator-kompendium"

aux_links:
  "Datorteknik (PDF)": "/dator-kompendium/assets/pdf/datorteknik.pdf"
  "Nätverk (PDF)": "/dator-kompendium/assets/pdf/network.pdf"

# Inställningar för att snygga till menyn (valfritt men rekommenderat)
heading_anchors: true
